pydantic/FastUI

python/demo/main.py

fix demois missing space

---

README.md
packages/fastui-bootstrap/src/index.tsx
packages/fastui-prebuilt/src/main.scss
packages/fastui/src/components/FormField.tsx
packages/fastui/src/components/index.tsx
python/demo/forms.py
python/fastui/components/__init__.py
python/fastui/components/forms.py
python/fastui/json_schema.py

ref: https://github.com/samuelcolvin/FastUI/issues/32

Add toggle switches support

---

packages/fastui/src/components/image.tsx
packages/fastui/src/components/index.tsx
python/demo/components_list.py
python/fastui/components/__init__.py

Add Image component support

---

demo/main.py

There is a broken link in this project. So I fixed it.
https://github.com/samuelcolvin/FastUI/tree/main/python/demo --> https://github.com/samuelcolvin/FastUI/tree/main/demo
This broken link was found with [link-inspector](https://github.com/justindhillon/link-inspector). If you find this pr useful, give the project a star ⭐
Signed off: [justin.singh.dhillon@gmail.com](mailto:justin.singh.dhillon@gmail.com)

Fix Broken Link

---

demo/main.py

Noticed broken link during [Python Bytes live stream](https://www.youtube.com/watch?v=oI_CxELGD8I).

docs: fix-broken-link

---

src/npm-fastui/src/dev.tsx
src/python-fastui/fastui/dev.py
src/python-fastui/tests/test_dev.py

Previously, the dev reload logic would reconnect whenever it got a 200 response, which meant with  a dev server than returns 200 for all routes, the dev logic was constantly reconnecting.
With this, it only reconnects if it gets a response starting with a specific string `'fastui-dev-reload'`,
Also connect to the endpoint defined by `rootUrl`.
cc @dmontagu @JonasKs.

require a magic response for dev reload server to reconnect

---

demo/tests.py
src/python-fastui/fastui/components/__init__.py
src/python-fastui/tests/test_json_schema.py

This is fix for #129 Demo code /docs Fetch error Internal Server Error /openapi.json 
**Issue:**
when generating openapi schema for fastui component, for navibar component, default value for key = "required" is missing 
**Solution:**
Add default value when generating schema
Note:
In docs some api point loading still very slow due to known issue: see https://github.com/pydantic/FastUI/issues/58

Fix issue with missing required field default value in Navbar JSON schema.

---

README.md

Solved Issue #126 
Modified the code in the sample to latest version where
c.Table[User](
data=users,
has been changed to 
c.Table(
data=users,
data_model=User,

Added data_model=User

---

demo/forms.py
src/npm-fastui-bootstrap/src/index.tsx
src/npm-fastui/src/components/FormField.tsx
src/npm-fastui/src/components/index.tsx
src/npm-fastui/src/models.d.ts
src/python-fastui/fastui/components/forms.py
src/python-fastui/fastui/forms.py
src/python-fastui/fastui/json_schema.py
src/python-fastui/tests/test_forms.py

fixes #116.
Adds the possibility to annotate your `str` field in the Pydantic model as `Textarea`, which renders it accordingly in the frontend.

Added textarea as form field

---

src/npm-fastui/src/components/FormField.tsx
src/npm-fastui/src/models.d.ts
src/python-fastui/fastui/components/forms.py

Hi! Awesome job on yet another repository! 👏
Before this
passing a list to `ModelForm(initial={"some_field": SOME_LIST})` didn't work.
See https://github.com/pydantic/FastUI/issues/91
Mini example (not compilable):
```python
from fastui import components as c
from pydantic import BaseModel
@router.get("/some-api-path",  response_model=FastUI,  response_model_exclude_none=True)
def some_route() -> list[c.AnyComponent]:
return [c.ModelForm(
model=SelectForm,
submit_url="./some-submit-url",
initial={"tools": [MyEnum.stick]},
)]
class MyEnum(str, Enum):
hammer = "hammer"
stick = "stick"
class SelectForm(BaseModel):
tools: list[MyEnum] = Field(default_factory=list)
```

fix: support finding initial value from a list of values

---

demo/components_list.py
src/npm-fastui-bootstrap/src/index.tsx
src/npm-fastui-prebuilt/src/main.scss
src/npm-fastui/src/models.d.ts
src/python-fastui/fastui/class_name.py
src/python-fastui/fastui/components/__init__.py

Fixes #22 for `Button` components.

Add named styles to buttons

---

src/npm-fastui/src/components/FormField.tsx
src/npm-fastui/src/models.d.ts
src/python-fastui/fastui/components/forms.py
src/python-fastui/fastui/json_schema.py

couldn't add it to the `Select` from `react-select` as it seems it doesn't support it - i get the following error message:
```
Property autoComplete does not exist on type
IntrinsicAttributes & Omit<PublicBaseSelectProps<unknown, boolean, GroupBase<unknown>>, StateManagedPropKeys> & Partial<...> & StateManagerAdditionalProps<...> & RefAttributes<...>
```
not sure what to do for that one.
should close https://github.com/pydantic/FastUI/issues/92

add `autocomplete` to `textarea` and `select`

---

demo/sse.py
package-lock.json
src/npm-fastui/package.json
src/npm-fastui/src/components/ServerLoad.tsx
src/npm-fastui/src/models.d.ts
src/npm-fastui/src/tools.ts
src/python-fastui/fastui/components/__init__.py

means:
* SSE connections don't automatically reconnect
* we can use methods other than `GET`
* we can include headers for auth
Partly resolves #171

SSE using `@microsoft/fetch-event-source` so we can post and control more

---

src/npm-fastui-bootstrap/package.json
src/npm-fastui/src/events.ts

https://pypi.org/project/codespell
```diff
-  "description": "Boostrap renderer for FastUI",
+  "description": "Bootstrap renderer for FastUI",
^
-  // fireEventImpl is recursive, but it doens't make sense for fireEvent to have fireEventImpl as a dep
+  // fireEventImpl is recursive, but it doesn't make sense for fireEvent to have fireEventImpl as a dep
^
```

Fix typos discovered by codespell

---

src/npm-fastui-bootstrap/src/pagination.tsx

fixes #142
https://github.com/pydantic/FastUI/assets/86600518/82bf562f-e007-41b3-90a5-6fdd0b353d9d
PR based on the comment: https://github.com/pydantic/FastUI/issues/142#issuecomment-1874416804
however there might have been a reason for the conditional statement that i am not aware of

fix page goto for page 1

---

src/npm-fastui/src/components/details.tsx
src/npm-fastui/src/components/table.tsx

This is the old view that shows `-` instead of `0`.
By this change it will only shows `-` for `undefined`

Fix display `0` on `DisplayLookup`

---

src/npm-fastui-bootstrap/src/pagination.tsx
src/npm-fastui/src/models.d.ts
src/python-fastui/fastui/components/tables.py

Fixes https://github.com/pydantic/FastUI/issues/203

Make pagination query param configurable

---

src/npm-fastui/src/components/FormField.tsx

add `onchange` to props for field input and bool

---

.github/workflows/ci.yml

CI error
```
The version '3.8' with architecture 'arm64' was not found for macOS 14.4.1.
```

Change CI to use `macos-13` for Python 3.8 and 3.9

---

src/python-fastui/fastui/json_schema.py
src/python-fastui/tests/test_forms.py

Fix description for array-like fields

---

.github/workflows/ci.yml
Makefile
README.md
build-docs.sh
demo/main.py
docs/api/typescript_components.md

Also makes local builds more friendly for developers who don't have insiders access to mkdocstrings :).

Add docs link to demo, disable typescript docs for now

---

src/python-fastui/fastui/components/tables.py
src/python-fastui/tests/test_tables_display.py

Add support for `computed_field` in `Table` component.

---

src/python-fastui/fastui/components/display.py
src/python-fastui/tests/test_tables_display.py

Fixes https://github.com/pydantic/FastUI/issues/186

Respect computed_field title in Details

---

src/npm-fastui/src/components/display.tsx

This PR allows FastUI components to be used as the values of DataModel's passed into Table and Details components.  This means that one can have a column in a table that is an Image, Button, etc.
For example, let's say I have an object with a name and an image.
```python
from pydantic import BaseCase
import fastui.components as c
class MyType(BaseClass):
name: str
icon: c.Image
my_object = MyType(name="meowzer", icon=c.Image(src="image.png"))
c.Page(
components=[
c.Details(data=my_object)
]
)
```
Before this PR:
| | |
| -- | -- |
| name | meowzer |
| icon | src: image.png, type: Image, |
After this PR:
| | |
| -- | -- |
| name | meowzer |
| icon | ![image](https://github.com/pydantic/FastUI/assets/381432/2d28ef07-9f6a-4a76-9500-271d76146269) |
FYI: @samuelcolvin @sydney-runkle 
Note: …

Allow nesting subcomponents like Images inside of Tables, Details, etc.

---

demo/tables.py
src/npm-fastui/src/components/display.tsx

Also added an example to the Users table. 
Addresses: https://github.com/pydantic/FastUI/issues/248

task: implement DisplayMarkdown

---

demo/forms.py
demo/tests.py

fix scalar as list with multi selects

---

demo/tests.py
src/npm-fastui/src/components/details.tsx
src/npm-fastui/src/models.d.ts
src/python-fastui/fastui/components/display.py
src/python-fastui/tests/test_tables_display.py

Fixes https://github.com/pydantic/FastUI/issues/185

Allow Display in Details

---

src/npm-fastui/src/components/display.tsx
src/npm-fastui/src/models.d.ts
src/python-fastui/fastui/components/display.py

Naive implementation, hardcoding USD display

Add `currency` to `DisplayMode`
